// Matter.js module aliases for convenient access to common Matter.js components.
const Engine = Matter.Engine; // Manages the physics simulation.
const Render = Matter.Render; // Renders the simulation to the canvas.
const Runner = Matter.Runner; // Provides a game loop utility.
const Composites = Matter.Composites; // For creating composite bodies like stacks and chains.
const Constraint = Matter.Constraint; // For creating constraints between bodies.
const MouseConstraint = Matter.MouseConstraint; // For adding mouse control.
const Mouse = Matter.Mouse; // Represents the mouse input.
const Composite = Matter.Composite; // A container for bodies, constraints, and other composites.
const Bodies = Matter.Bodies; // Factory for creating rigid bodies (circles, rectangles, etc.).
const Events = Matter.Events; // For listening to engine and mouse events.

// --- UI Elements ---
// DOM elements used for user interaction and displaying information.
const sensorInfoDiv = document.getElementById('sensorInfo'); // Div to display sensor status and data.
const requestSensorButton = document.getElementById('requestSensorButton'); // Button to request sensor permission.

// --- Engine and Renderer Setup ---
// Initializes the Matter.js physics engine and the renderer.
const engine = Engine.create({
    enableSleeping: true, // Allows bodies to "sleep" when inactive for a period, improving performance.
    positionIterations: 10 // Number of position iterations per update. Higher values improve simulation stability/quality.
});
const world = engine.world; // The main container for all bodies, constraints, and composites in the simulation.

const gravityMagnitude = 10; // Defines the overall strength/magnitude of the gravitational force.
engine.gravity.y = gravityMagnitude; // Sets initial gravity to point downwards along the Y-axis.
engine.gravity.x = 0; // No initial horizontal gravity.

// Creates the renderer, which is responsible for drawing the simulation on the canvas.
const render = Render.create({
    element: document.body, // The HTML element where the canvas will be inserted.
    engine: engine, // The physics engine instance to render.
    canvas: document.querySelector('canvas'), // Explicitly targets the <canvas> element defined in index.html.
    options: {
        width: window.innerWidth, // Sets the initial width of the canvas to the browser window's width.
        height: window.innerHeight, // Sets the initial height of the canvas to the browser window's height.
        wireframes: false, // If true, renders bodies as wireframes; false renders them as solid shapes.
        background: '#111' // Background color of the rendering canvas.
    }
});

Render.run(render); // Starts the rendering loop.
const runner = Runner.create(); // Creates a default runner instance to manage the engine's update loop.
Runner.run(runner, engine); // Starts the physics simulation loop.

// --- Chain Creation ---
// This section defines the properties and constructs the physics-based chain.

// Creates a new collision group. Bodies in the same group (if the group ID is negative, as generated by nextGroup(true))
// will not collide with each other. This is essential for the chain segments to overlap without interacting.
const group = Matter.Body.nextGroup(true);

// Parameters for the chain segments and their connections.
const segmentLength = 30; // Approximate visual length of each link in the chain (used for constraint length).
const segmentRadius = 10; // Radius of the circular bodies that form the chain segments.
const numSegments = 15;   // Number of segments that make up the chain.
const stiffness = 0.6;    // Stiffness of the constraints connecting chain segments (0 to 1). Higher is more rigid.
const damping = 0.2;      // Damping applied to the constraints, reducing oscillations (0 to 1). Higher is more damped.
const chainStartX = window.innerWidth / 2; // Initial X coordinate for the chain's starting point (center of the screen).
const chainStartY = 0; // Initial Y coordinate for the chain's starting point (top of the screen).

// Creates a stack of circular bodies (segments) for the chain.
// Composites.stack(xx, yy, columns, rows, columnGap, rowGap, callback)
// Here, it creates a single column (numSegments rows, 1 column) of circles.
const chain = Composites.stack(chainStartX, chainStartY, numSegments, 1, 0, 0, function(x, y) {
    // This callback function is invoked for each segment being created.
    return Bodies.circle(x, y, segmentRadius, {
        collisionFilter: { group: group }, // Assigns the segment to the collision group.
        frictionAir: 0.1, // Air friction acting on each segment, slows down movement over time.
        slop: 0.2,        // Amount of overlap bodies can have before separating (helps with stability and appearance).
        render: { // Visual properties for the chain segments
            fillStyle: '#00FFFF', // Aqua - for a bright, light-like appearance
            strokeStyle: '#FFFFFF', // White - for a clear outline
            lineWidth: 2 // Slightly thicker outline for better definition
        }
    });
});

// Connects the chain segments with constraints to form the actual chain structure.
// Composites.chain(composite, xOffsetA, yOffsetA, xOffsetB, yOffsetB, options)
// xOffsetA/B and yOffsetA/B define the attachment points on the bodies relative to their centers.
// Here, 0.5 means the right side of a segment, -0.5 means the left side of the next.
Composites.chain(chain, 0.5, 0, -0.5, 0, {
    stiffness: stiffness,
    length: segmentLength * 0.1, // Desired length of the links connecting segments.
                                 // This is a fraction of segmentLength, making links short and tight.
    damping: damping,
    render: { // Visual properties for the links (constraints) between chain segments
        type: 'line', // Render constraints as lines.
        strokeStyle: '#AAAAAA', // Lighter grey - to complement the "light" segments
        lineWidth: 1
    }
});

// Anchors the first segment of the chain to a fixed point at the top of the screen.
const firstSegment = chain.bodies[0]; // Get the first body (segment) in the chain composite.
const anchor = { x: chainStartX, y: 5 }; // Define the world-space coordinates for the anchor point.

// Add the chain composite and the anchor constraint to the world.
Composite.add(world, [
    chain, // The entire chain (all segments and their connecting constraints).
    Constraint.create({
        bodyA: null, // If bodyA is null, pointA is treated as a fixed world-space coordinate.
        pointA: anchor, // The fixed point in the world to attach to.
        bodyB: firstSegment, // The body (first chain segment) to attach to the anchor.
        pointB: { x: 0, y: 0 }, // The offset on bodyB where the constraint attaches (center of the segment).
        stiffness: 0.5, // Stiffness of the anchor constraint.
        length: 0 // Desired length of the constraint (0 means it tries to keep pointB at pointA).
    })
]);

// --- Interaction & Pull Limit ---
// This section handles mouse interaction for dragging chain segments and implements a pull limit
// with visual and haptic (vibration) feedback.

// Creates a mouse object that tracks mouse events on the renderer's canvas.
const mouse = Mouse.create(render.canvas);

// Creates a mouse constraint, which allows interacting with bodies in the engine using the mouse.
const mouseConstraint = MouseConstraint.create(engine, {
    mouse: mouse, // The mouse object to use for tracking input.
    constraint: {
        stiffness: 0.1, // Stiffness of the constraint when dragging a body. Lower values make it more springy.
        render: { visible: false } // Makes the constraint line (if any) invisible during dragging.
    }
});

Composite.add(world, mouseConstraint); // Adds the mouse constraint to the world to enable interaction.
render.mouse = mouse; // Connects the renderer's mouse to the created mouse object for proper coordinate mapping.

// Variables to manage the state of a dragged chain segment and the pull limit logic.
let draggedChainBody = null; // Stores a reference to the chain segment currently being dragged. Null if none.
let startPullX = 0; // Stores the initial X position of the mouse when a chain segment drag started.
let startPullY = 0; // Stores the initial Y position of the mouse when a chain segment drag started.
const maxPullDistance = 100; // Maximum distance (in pixels) a segment can be pulled from its initial drag point.
let vibrationTriggeredThisDrag = false; // Flag to ensure vibration feedback occurs only once per pull limit breach.

// Event listener for when a mouse drag starts on a body within the mouse constraint's scope.
Events.on(mouseConstraint, 'startdrag', (event) => {
    // Check if the body being dragged is one of the chain segments.
    if (chain.bodies.includes(event.body)) {
        draggedChainBody = event.body; // Store the dragged segment.
        startPullX = mouse.position.x; // Record the mouse's current X position as the start of the pull.
        startPullY = mouse.position.y; // Record the mouse's current Y position as the start of the pull.
        vibrationTriggeredThisDrag = false; // Reset the vibration flag for this new drag action.

        // Clean up any lingering temporary styles if a previous drag might have ended abruptly
        // without the 'enddrag' event firing correctly (edge case).
        if (draggedChainBody._originalRenderStyle) {
            delete draggedChainBody._originalRenderStyle;
        }
    }
});

// Event listener for when a mouse drag ends.
Events.on(mouseConstraint, 'enddrag', (event) => {
    // Check if the body whose drag ended is the one we were tracking.
    if (draggedChainBody && event.body === draggedChainBody) {
        // Revert visual feedback if it was active (i.e., if _originalRenderStyle exists on the body).
        if (draggedChainBody._originalRenderStyle) {
            draggedChainBody.render.fillStyle = draggedChainBody._originalRenderStyle.fillStyle;
            draggedChainBody.render.strokeStyle = draggedChainBody._originalRenderStyle.strokeStyle;
            delete draggedChainBody._originalRenderStyle; // Clean up the temporary style property.
        }
        draggedChainBody = null; // Clear the reference, as no segment is being dragged now.
    }
});

// Event listener that fires just before each physics engine update (i.e., on each frame/tick of the simulation).
Events.on(engine, 'beforeUpdate', () => {
    // This block handles the logic that needs to be checked or updated continuously while a chain segment is dragged.
    if (draggedChainBody) {
        const deltaX = mouse.position.x - startPullX; // Horizontal distance dragged from the recorded start point.
        const deltaY = mouse.position.y - startPullY; // Vertical distance dragged from the recorded start point.
        const currentDistance = Math.sqrt(deltaX * deltaX + deltaY * deltaY); // Direct distance from the start point.

        // Check if the current drag distance exceeds the defined maximum pull distance.
        if (currentDistance > maxPullDistance) {
            // --- Visual Feedback for Max Pull ---
            // Change the segment's appearance to indicate the pull limit has been reached.
            if (!draggedChainBody._originalRenderStyle) { // Apply feedback style only if it hasn't been applied yet for this pull.
                // Store the segment's original style properties before overriding them.
                draggedChainBody._originalRenderStyle = {
                    fillStyle: draggedChainBody.render.fillStyle,
                    strokeStyle: draggedChainBody.render.strokeStyle
                };
                // Apply the "limit reached" visual style.
                draggedChainBody.render.fillStyle = '#ffcc00'; // Bright yellow fill
                draggedChainBody.render.strokeStyle = '#ffffff'; // White border for contrast
            }

            // --- Vibration Feedback ---
            // Provide haptic feedback if the Vibration API is supported by the browser.
            if (!vibrationTriggeredThisDrag) { // Trigger vibration only once per breach to avoid continuous vibration.
                if (navigator.vibrate) {
                     navigator.vibrate([1, 50, 1]); // A short, sharp vibration pattern: vibrate 1ms, pause 50ms, vibrate 1ms.
                } else {
                    console.log("Vibration API not supported"); // Log if Vibration API is unavailable.
                }
                vibrationTriggeredThisDrag = true; // Set flag to prevent re-triggering vibration in this drag instance.
            }

            // --- Clamp Mouse Position ---
            // This is a crucial part: it prevents the dragged body from actually moving further than maxPullDistance
            // from its start point by effectively overriding Matter.js's internal mouse position for this tick.
            const ratio = maxPullDistance / currentDistance; // Calculate the ratio to scale down the pull vector.
            const clampedX = startPullX + deltaX * ratio; // Calculate the mouse X position, clamped to the max distance circle.
            const clampedY = startPullY + deltaY * ratio; // Calculate the mouse Y position, clamped to the max distance circle.

            // Update Matter.js's internal representation of the mouse's current position to the clamped values.
            // This influences how Matter.js applies forces or moves the dragged body via the mouse constraint.
            mouse.position.x = clampedX;
            mouse.position.y = clampedY;

            // It's also good practice to update mouse.absolute and mouse.offset if they are used elsewhere
            // or by other parts of Matter.js, though for simple mouse constraints, updating mouse.position is often sufficient.
            const canvasBounds = render.canvas.getBoundingClientRect(); // Get canvas position for absolute calculation.
            mouse.absolute.x = mouse.position.x + canvasBounds.left + window.scrollX;
            mouse.absolute.y = mouse.position.y + canvasBounds.top + window.scrollY;
            mouse.offset.x = mouse.position.x; // Offset is typically relative to the canvas.
            mouse.offset.y = mouse.position.y;
        } else {
            // --- Revert Visual Feedback if distance is below max ---
            // If the segment is pulled back within the limit (or was never over it), ensure its style is original.
            if (draggedChainBody._originalRenderStyle) { // Check if the feedback style was previously applied.
                draggedChainBody.render.fillStyle = draggedChainBody._originalRenderStyle.fillStyle;
                draggedChainBody.render.strokeStyle = draggedChainBody._originalRenderStyle.strokeStyle;
                delete draggedChainBody._originalRenderStyle; // Clean up the temporary style property.
            }
        }
    }
});

// --- Gyroscope Integration ---
// This section handles device orientation events (from gyroscope/accelerometer)
// to dynamically control the direction of gravity in the simulation.

// Callback function to process device orientation data.
function handleOrientation(event) {
    // DeviceOrientationEvent properties:
    // event.beta: Front-to-back tilt in degrees. Range can vary (e.g., -180 to 180 or 0 to 360).
    // event.gamma: Left-to-right tilt in degrees. Range can vary (e.g., -90 to 90).
    // event.alpha: Compass direction in degrees (0 to 360). Not typically used for gravity simulation.

    // Check if essential sensor data (beta and gamma for tilt) is available.
    if (event.beta === null || event.gamma === null) {
         sensorInfoDiv.innerHTML = 'Sensor data incomplete.'; // Inform the user if critical data is missing.
         // Optionally, could revert to a default gravity if sensor data becomes unavailable during use.
         // engine.gravity.x = 0;
         // engine.gravity.y = gravityMagnitude; // Default vertical gravity.
         return; // Exit if data is insufficient.
    }

    const beta = event.beta;   // Represents tilting the phone forward (positive beta) or backward (negative beta).
    const gamma = event.gamma; // Represents tilting the phone right (positive gamma) or left (negative gamma).

    // Convert tilt angles from degrees to radians for use with trigonometric functions (Math.sin).
    const betaRad = beta * (Math.PI / 180);
    const gammaRad = gamma * (Math.PI / 180);

    // Calculate gravity components based on tilt.
    // The mapping of tilt axes (beta, gamma) to gravity axes (gx, gy) can vary based on desired effect
    // and how the device reports orientation. This is a common mapping:
    // - Gamma (left/right tilt) controls the x-axis gravity. Tilting the device right makes things fall "right".
    // - Beta (forward/backward tilt) controls the y-axis gravity. Tilting the device forward makes things fall "down" (towards user).
    // The signs (+/-) of gx and gy might need adjustment depending on the specific device's coordinate system
    // and browser consistency to achieve the intuitive "falling towards the ground" effect.
    const gx = gravityMagnitude * Math.sin(gammaRad); // Gravity component along X-axis.
    const gy = gravityMagnitude * Math.sin(betaRad);  // Gravity component along Y-axis.

    // Update the engine's gravity vector with the newly calculated components.
    engine.gravity.x = gx;
    engine.gravity.y = gy;

    // Update the sensor information display with current sensor readings and calculated gravity.
    // Using innerHTML allows for the use of <br> tags, improving the readability of the displayed information.
    sensorInfoDiv.innerHTML = `Sensor Active<br>Beta (F/B): ${beta.toFixed(1)}°<br>Gamma (L/R): ${gamma.toFixed(1)}°<br>Gravity: x=${gx.toFixed(2)}, y=${gy.toFixed(2)}`;
}

// Function to request permission from the user to access Device Orientation API.
// This is particularly necessary for modern browsers and operating systems (e.g., iOS 13+)
// which require explicit user consent for privacy reasons.
function requestDeviceOrientationPermission() {
    // Check if the modern permission API (DeviceOrientationEvent.requestPermission) is available.
    if (typeof DeviceOrientationEvent !== 'undefined' && typeof DeviceOrientationEvent.requestPermission === 'function') {
        // This is the standard path for iOS 13+ and other browsers implementing this specific permission model.
        DeviceOrientationEvent.requestPermission()
            .then(permissionState => {
                if (permissionState === 'granted') {
                    // Permission was granted by the user.
                    window.addEventListener('deviceorientation', handleOrientation); // Start listening to orientation events.
                    sensorInfoDiv.innerHTML = 'Motion sensor permission granted.<br>Waiting for data...';
                    requestSensorButton.style.display = 'none'; // Hide the button as it's no longer needed.
                } else {
                    // Permission was denied by the user.
                    sensorInfoDiv.innerHTML = 'Motion sensor permission denied.';
                    requestSensorButton.disabled = true; // Disable the button to prevent further requests.
                }
            })
            .catch(error => {
                 // An error occurred during the permission request process.
                 console.error("DeviceOrientationEvent permission error:", error);
                 sensorInfoDiv.innerHTML = `Could not enable motion sensors:<br>${error.message}`;
                 requestSensorButton.disabled = true; // Disable button on error.
            });
    } else if ('DeviceOrientationEvent' in window) {
        // This path is for older browsers or environments where DeviceOrientationEvent exists
        // but does not use the requestPermission model (e.g., Android browsers, older desktop browsers).
        // In these cases, permission might be implicitly granted, handled by global browser settings,
        // or not required in the same way.
        console.log("Adding deviceorientation listener directly (no explicit permission API or already granted).");
        window.addEventListener('deviceorientation', handleOrientation);
        sensorInfoDiv.innerHTML = 'Motion sensors active (no permission needed).<br>Waiting for data...';
        requestSensorButton.style.display = 'none'; // Hide the button.
    } else {
        // The DeviceOrientationEvent API is not supported by the browser or device at all.
        sensorInfoDiv.innerHTML = 'Motion sensors (Device Orientation API) are not supported on this browser or device.';
        requestSensorButton.disabled = true; // Disable button.
        requestSensorButton.textContent = 'Not Supported'; // Update button text to reflect unavailability.
    }
}

// Add an event listener to the "Enable Motion Sensors" button.
// Clicking this button will trigger the requestDeviceOrientationPermission function.
requestSensorButton.addEventListener('click', requestDeviceOrientationPermission);

// --- Fit to window ---
// This section ensures that the Matter.js rendering viewport correctly fits the browser window
// and dynamically adapts when the window is resized.

// Initially sets the renderer's view to encompass the entire current window size.
// Render.lookAt(render, bodies, padding, center) can also be used to focus on specific bodies or areas.
// Here, it's used to set the overall view boundaries from {min: {x,y}} to {max: {x,y}}.
Render.lookAt(render, {
    min: { x: 0, y: 0 }, // Defines the top-left corner of the viewport.
    max: { x: window.innerWidth, y: window.innerHeight } // Defines the bottom-right corner of the viewport.
});

// Adds an event listener that triggers when the browser window is resized.
window.addEventListener('resize', () => {
    // Update the renderer's options to match the new window dimensions.
    render.options.width = window.innerWidth;
    render.options.height = window.innerHeight;

    // Update the HTML canvas element's dimensions directly.
    render.canvas.width = window.innerWidth;
    render.canvas.height = window.innerHeight;

    // Re-apply Render.lookAt to adjust the simulation's viewport to the new dimensions.
    // This ensures that the simulation content scales or re-centers correctly within the new window size.
    Render.lookAt(render, {
        min: { x: 0, y: 0 },
        max: { x: window.innerWidth, y: window.innerHeight }
    });

    // Note on element positioning:
    // If other simulation elements (like the chain's anchor point) were positioned based on
    // the initial window size in a way that doesn't automatically adapt (e.g., using absolute pixel values
    // not relative to the center or edges), their positions might need to be recalculated here.
    // The current chain anchor is defined by `chainStartX = window.innerWidth / 2` at the start.
    // This means its world X-coordinate is fixed after initialization. If dynamic re-centering of
    // the entire simulation or specific elements like the anchor was desired upon resize,
    // that logic would be added here. For example:
    // anchor.x = window.innerWidth / 2; // To re-center the anchor horizontally.
    // And then potentially update the constraint if its definition depends on `anchor`'s world position.
    // However, for this demo, the anchor remains at its initial world position.
});
